### ISSUE TITLE
[BUG] Failed to run builtin commands with LazyVim

### ISSUE THREAD

**Issue by DvdBr3o** [Mythos-404/xmake.nvim#13]
## Error Description
Pretty much akin to #12 but this is under **LazyVim** whereas the #12 is under **lazy.vim**.
Failed to run `:Xmake debug <target_name>` where `<target_name>` is able to be run with `xmake run <target_name>` in terminal.
![屏幕截图 2024-11-11 210937](https://github.com/user-attachments/assets/8659e341-f4d1-4aa3-9236-1535761ae4b2)
And when I run `:Xmake debug`, it failed to find any target:
![屏幕截图 2024-11-11 210948](https://github.com/user-attachments/assets/f71b3f0d-5444-430e-810d-d63f2387d353)

## Method of reproduction
Use LazyVim template and add the following codes under arbitary file in `nvim/lua/plugins/`:
```lua
return {
  {
    "Mythos-404/xmake.nvim",
    version = "^3",
    lazy = false,
    event = "BufReadPost xmake.lua",
    config = true,
    dependencies = {
      "stevearc/dressing.nvim",
      "rcarriga/nvim-notify",
    },
  },
}
```

## Screenshots (optional)
Already in *Error Description*.

## Environmental Information

- System: Windows 23H2
- Shell: nushell / neovide
- Terminal: Windows Terminal / neovide
- neovim version: NVIM v0.10.1
- xmake version: xmake v2.9.5+HEAD.d30de52e9

## Minimum Reproducible Configuration
Already in *Method of reproduction*.
Here is a quick reproduction repo: [DvdBr3o/xmake-nvim-reprod](https://github.com/DvdBr3o/xmake-nvim-reprod).

**Comment by DvdBr3o** [comment]
And it seems that the notice is somehow conflicting with LazyVim default notice plugin (from 13.x it's `Snacks.notifier` in [folke/snacks.nvim](https://github.com/folke/snacks.nvim)):
![image](https://github.com/user-attachments/assets/40f66776-1bc0-4987-99f9-f4982fb74690)
It couldn't be better if you could tackle the integration with it. But if you cannot help with it,  it doesn't matter as well.
But anyway please add `-y` for `xmake project -k compile_commands` in your implementation. Because the phenomena shown in capture did never stop... I assume that it is caused by the inquery from xmake of whether to install uninstalled package.

**Comment by Mythos-404** [comment]
For the first issue, please run `:Lazy sync` to update and sync your plugins.

As for the second issue, since the new notification plugin requires some time for adaptation, could you please open a new issue to help us keep track? Thanks for your understanding!

**Comment by DvdBr3o** [comment]
The new commit fixed the problem. Thanks.

Regarding the second issue, I will raise a new issue later on :)
