### ISSUE TITLE
[BUG] The Notifier Adaption with LazyVim

### ISSUE THREAD

**Issue by DvdBr3o** [Mythos-404/xmake.nvim#14]
**Error Description**
1. The notifier function seems out of adaption with LazyVim default notifier plugin (from 13.x it's `Snacks.notifier` in [folke/snacks.nvim](https://github.com/folke/snacks.nvim))
2. The compile_commands notifier never stops if the project requires not installed packages. (because xmake keeps inquiring `y/n` to install the not installed packages)

**Method of reproduction**
1. Create a xmake project with `add_requires` where the packages are unistalled.
2. Save `xmake.lua` to trigger the auto update. 

**Screenshots (optional)**
![image](https://github.com/user-attachments/assets/40f66776-1bc0-4987-99f9-f4982fb74690)

**Environmental Information**

- System: Windows 23H2
- Shell: nushell/neovide
- Terminal: WindowsTerminal/neovide
- neovim version: v0.10.1
- xmake version: v2.9.6+HEAD.abd15c255

**Minimum Reproducible Configuration**
```lua
-- xmake.lua
add_requires("glfw") -- Make sure `glfw` is not installed.
```

**Comment by Mythos-404** [comment]
The bug occurred because the `notifier` module in the `folke/snacks.nvim` plugin used a different configuration replacement method than `rcarriga/nvim-notify`. This issue has now been resolved.

Please don’t forget to run `:Lazy sync`.

**Comment by Mythos-404** [comment]
Could you run `:Lazy log xmake.nvim` and confirm if the first hash displayed is `b1ebed4`?

**Comment by Mythos-404** [comment]
You can use this mini config for testing.

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"git@github.com:folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"Mythos-404/xmake.nvim",
		lazy = true,
		version = "^3",
		event = "BufReadPost xmake.lua",
		config = true,
	},
	{
		"folke/snacks.nvim",
		priority = 1000,
		lazy = false,
		opts = {},
	},
})

vim.keymap.set("n", "<C-s>", ":w<CR>")
```

Save it to a file, then open `nvim` with `nvim -u <save-file-name>.lua ./xmake.lua`.
Run `:Lazy sync` to sync plugins, exit, and reopen `nvim` using the same command as before. 
Press `<C-s>` to test if the `auto compile_commands.json` feature works as expected.

**Comment by DvdBr3o** [comment]
> Could you run `:Lazy log xmake.nvim` and confirm if the first hash displayed is `b1ebed4`?

Yeah, it is `b1ebed4` in my own config.

![屏幕截图 2024-11-13 235152](https://github.com/user-attachments/assets/11da3059-84c1-4ecb-a9f9-7d5f00828177)



> You can use this mini config for testing.
> 
> ```lua
> local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
> if not vim.loop.fs_stat(lazypath) then
> 	vim.fn.system({
> 		"git",
> 		"clone",
> 		"--filter=blob:none",
> 		"git@github.com:folke/lazy.nvim.git",
> 		"--branch=stable", -- latest stable release
> 		lazypath,
> 	})
> end
> vim.opt.rtp:prepend(lazypath)
> 
> require("lazy").setup({
> 	{
> 		"Mythos-404/xmake.nvim",
> 		lazy = true,
> 		version = "^3",
> 		event = "BufReadPost xmake.lua",
> 		config = true,
> 	},
> 	{
> 		"folke/snacks.nvim",
> 		priority = 1000,
> 		lazy = false,
> 		opts = {},
> 	},
> })
> 
> vim.keymap.set("n", "<C-s>", ":w<CR>")
> ```
> 
> Save it to a file, then open `nvim` with `nvim -u <save-file-name>.lua ./xmake.lua`. Run `:Lazy sync` to sync plugins, exit, and reopen `nvim` using the same command as before. Press `<C-s>` to test if the `auto compile_commands.json` feature works as expected.

And with this config the notifier works in proper behaviour...

<img width="846" alt="image" src="https://github.com/user-attachments/assets/df9a00f0-22b5-4c95-8002-481e6c7a85e9">


I have no clue which part of my config makes the conflict happens...

Is there any approach to log something useful about this?

**Comment by DvdBr3o** [comment]
This is a list of my extensions from `:Lazy`. Is anyone of them suspicious?

```
  Loaded (40)   
    ● auto-dark-mode.nvim 27.83ms  start
    ● bufferline.nvim 4.21ms  VeryLazy
    ● clangd_extensions.nvim 0.55ms 󰢱 clangd_extensions  nvim-lspconfig
    ● cmp-nvim-lsp 2.36ms 󰢱 cmp_nvim_lsp  nvim-lspconfig
    ● conform.nvim 2.32ms 󰢱 conform  LazyVim
    ● dashboard-nvim 1.41ms  start
    ● edgy.nvim 3.73ms  VeryLazy
    ● flash.nvim 3.03ms  VeryLazy
    ● gitsigns.nvim 20.61ms  LazyFile
    ● hydra.nvim 2.2ms  multicursors.nvim
    ● indent-blankline.nvim 4.72ms  LazyFile
    ● lazy.nvim 23.47ms  init.lua
    ● lazydev.nvim 3.28ms  lua
    ● LazyVim 19.57ms  start
    ● lualine.nvim 26.39ms  VeryLazy
    ● mason-lspconfig.nvim 0.2ms  nvim-lspconfig
    ● mason.nvim 25.2ms  nvim-lspconfig
    ● mini.ai 1.59ms  VeryLazy
    ● mini.icons 1.12ms 󰢱 mini.icons  LazyVim
    ● mini.pairs 4.22ms  VeryLazy
    ● monokai-pro.nvim 0.51ms colorscheme monokai-pro  LazyVim
    ● multicursors.nvim 10.21ms  VeryLazy
    ● neo-tree.nvim 17.46ms 󰢱 neo-tree  LazyVim
    ● noice.nvim 2.84ms  VeryLazy
    ● nui.nvim 0.82ms  neo-tree.nvim
    ● nvim-lint 3.23ms  LazyFile
    ● nvim-lspconfig 45.13ms  LazyFile
    ● nvim-treesitter 17.32ms  start
    ● nvim-treesitter-textobjects 2.75ms  VeryLazy
    ● nvim-ts-autotag 3.11ms  LazyFile
    ● nvim-web-devicons 1ms  neo-tree.nvim
    ● persistence.nvim 1.02ms  start
    ● plenary.nvim 1.18ms  neo-tree.nvim
    ● snacks.nvim 1.09ms  start
    ● todo-comments.nvim 3.25ms  LazyFile
    ● trouble.nvim 2.56ms 󰢱 trouble  lualine.nvim
    ● ts-comments.nvim 1.3ms  VeryLazy
    ● typescript.nvim 1.75ms  nvim-lspconfig
    ● which-key.nvim 1.88ms  VeryLazy
    ● xmake.nvim 3.54ms  BufReadPost xmake.lua

  Not Loaded (26)
    ○ catppuccin 
    ○ cmp-buffer  nvim-cmp 
    ○ cmp-emoji  nvim-cmp 
    ○ cmp-path  nvim-cmp 
    ○ dressing.nvim 
    ○ friendly-snippets  nvim-snippets 
    ○ generate.nvim  <leader>cI 
    ○ grug-far.nvim  <leader>sr (v)  <leader>sr  GrugFar 
    ○ LuaSnip 
    ○ luvit-meta 
    ○ markdown-preview.nvim  markdown  MarkdownPreview  MarkdownPreviewStop  MarkdownPreviewToggle 
    ○ mason-nvim-dap.nvim  DapInstall  DapUninstall 
    ○ material.nvim 
    ○ nvim-cmp  InsertEnter 
    ○ nvim-dap  <leader>d  <leader>d (v)  <leader>dB  <leader>db  <leader>dc  <leader>da  <leader>dC  <leader>dg  <leader>di  <leader>dj  <leader>dk  <leader>dl  <leader>do  <leader>dO  <leader>dp  <leader>dr  <leader>ds  <leader>dt  <leader>dw 
    ○ nvim-dap-ui  <leader>du  <leader>de  <leader>de (v)  nvim-dap 
    ○ nvim-dap-virtual-text  nvim-dap 
    ○ nvim-nio  nvim-dap-ui 
    ○ nvim-snippets  nvim-cmp 
    ○ SchemaStore.nvim 
    ○ symbols-outline.nvim  <leader>cs  SymbolsOutline 
    ○ tailwindcss-colorizer-cmp.nvim  nvim-cmp 
    ○ telescope-fzf-native.nvim  telescope.nvim 
    ○ telescope.nvim  <leader>,  <leader>/  <leader>:  <leader>fb  <leader>fc  <leader>ff  <leader>fF  <leader>fg  <leader>fr  <leader>fR  <leader>gc  <leader>gs  <leader>s"  <leader>sa  <leader>sb  <leader>sc  <leader>sC  <leader>sd  <leader>sD  <leader>sg  <leader>sG  <leader>sh  <leader>sH  <leader>sj  <leader>sk  <leader>sl  <leader>sM  <leader>sm  <leader>so  <leader>sR  <leader>sq  <leader>sw  <leader>sW  <leader>sw (v)  <leader>sW (v)  <leader>uC  <leader>ss  <leader>sS  <leader>fp  <leader><space>  Telescope 
    ○ toggleterm.nvim  <leader>tg  <C-`>  ToggleTerm 
    ○ tokyonight.nvim 
```

**Comment by Mythos-404** [comment]
[`DvdBr30.nvim`](https://github.com/DvdBr3o/DvdBr3o.nvim) Is the configuration in this repository your main configuration? If so, I’ll use it to troubleshoot the issue :)

**Comment by DvdBr3o** [comment]
Maybe `noice.nvim` is worth notice. It's one of the default plugins of LazyVim (I did not explicitly require it in my config).

But [`folke/noice.nvim`](https://github.com/folke/noice.nvim) depends on `nvim-notify`:

![image](https://github.com/user-attachments/assets/be5c7e7e-2538-447b-b9f9-f2cb73e6aeea)

**Comment by Mythos-404** [comment]
> Maybe `noice.nvim` is worth notice. It's one of the default plugins of LazyVim (I did not explicitly require it in my config).
> 
> But [`folke/noice.nvim`](https://github.com/folke/noice.nvim) depends on `nvim-notify`:
> 
> ![image](https://private-user-images.githubusercontent.com/77841210/385842433-be5c7e7e-2538-447b-b9f9-f2cb73e6aeea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MTQ5ODcsIm5iZiI6MTczMTUxNDY4NywicGF0aCI6Ii83Nzg0MTIxMC8zODU4NDI0MzMtYmU1YzdlN2UtMjUzOC00NDdiLWI5ZjktZjJjYjczZTZhZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDE2MTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNjcyNzMyNTg1OWQwNTdjYzQ3NjY5NDNlYTgxZDc0YTA0ZmZkYmM1MDEyYmY1MDVlN2ZiNzRlZGU3ZTJkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UxWLeG22UBg69mD9cc8kUfXcV_BUwkmP14CGd5U1520)

I'll give it a test.

**Comment by DvdBr3o** [comment]
Yeah, i tried disabling `noice.nvim` and it behaves properly and the same as the test you gave.

Maybe adaption with `noice.nvim` is also needed? But it turns complex since there are two notifier existing simultaneously...

**Comment by DvdBr3o** [comment]
> [`DvdBr30.nvim`](https://github.com/DvdBr3o/DvdBr3o.nvim) Is the configuration in this repository your main configuration? If so, I’ll use it to troubleshoot the issue :)

Yes, it is :)

**Comment by Mythos-404** [comment]
The issue occurred because after [`folke/noice.nvim`](https://github.com/folke/noice.nvim) injected `vim.notify`, it wrapped the `id` returned by `folke/snacks.nvim` or `rcarriga/nvim-notify` in a table, causing the malfunction.

It’s now fixed! Please run `:Lazy sync` and check if it’s working properly :)

**Comment by DvdBr3o** [comment]
Now it works! Thank u :)
