### ISSUE TITLE
[BUG] Failed to run builtin command

### ISSUE THREAD

**Issue by Horc-zh** [Mythos-404/xmake.nvim#16]
**错误描述**
無法使用内置命令

**重现方法**
我使用lazy下載了這個插件，但當我在命令行輸入Xmake run的時候:
![image](https://github.com/user-attachments/assets/845127fc-ffb3-4fb5-ac71-cb300978acd2)

**环境信息**

- 系統：windows11
- Shell ：powershell
- 終端：wezterm
- Neovim版本: NVIM v0.10.2  Build type: Release  LuaJIT 2.1.1713484068

- Xmake版本: xmake v2.9.6+HEAD.abd15c255
- 本插件的版本:![image](https://github.com/user-attachments/assets/2fed7014-82fd-4c20-834a-beea914bbb68)

**最低可复现配置**

使用了astronvim的community.lua安裝插件
```lua
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.cpp" },
  { import = "astrocommunity.completion.cmp-cmdline" },
  { import = "astrocommunity.utility.noice-nvim" },
  -- xmake
  {
    "Mythos-404/xmake.nvim",
    version = "^3",
    lazy = true,
    event = "BufReadPost",
    config = true,
  }
}

```
我要如何解決這個問題，感謝

**Comment by Mythos-404** [comment]
请问其他的命令可以正常工作吗？

**Comment by Horc-zh** [comment]
> 请问在项目中使用`xmake show --list=targets`这个命令的输出是什么?


输出了main，
以下是我的xmake.lua:
```lua
add_rules("plugin.compile_commands.autoupdate", { outputdir = "build" })

add_requires("fmt")
set_languages("c99", "cxx23")

target("main")
  set_kind("binary")
  add_packages("fmt")
  add_files("main.cpp")
```
main.cpp:
```cpp
#include <fmt/core.h>
#include <vector>

int main()
{
    std::vector<int> vec { 0, 1 };
    fmt::println("{} {}", vec[0], vec[1]);
    return 0;
}
```

对于其他命令可以见下图：
![image](https://github.com/user-attachments/assets/837fd44c-4708-47ae-a5d9-33fcf06c7e43)

**Comment by Mythos-404** [comment]
请问你开启`nvim`是用的什么方法, 如果是先打开单独的`nvim`, 在使用目录树插件打开文件的话有些东西是不能正常工作的.

你试一下`:lua require("xmake").command.init()`, 这个命令可以工作吗

**Comment by Horc-zh** [comment]
输入命令之后按下回车键没有反应，什么输出都没有：
![image](https://github.com/user-attachments/assets/969dab15-5a0d-4aaf-9ceb-23e81c623f08)
这是我在lazy插件中搜索xmake的结果：
![image](https://github.com/user-attachments/assets/0d9d47ee-eeff-47fb-80de-83fc0b712318)
开启nvim只是很简单的在wezterm中输入`nvim .`，如下：
![image](https://github.com/user-attachments/assets/c2d953ca-388d-4a74-9bb4-5025b82bd552)

**Comment by Horc-zh** [comment]
> 你试一下`:lua require("xmake").command.init()`, 这个命令可以工作吗.
> 
> 请问你开启`nvim`是用的什么方法?


输入命令之后按下回车键没有反应，什么输出都没有：
![image](https://github.com/user-attachments/assets/969dab15-5a0d-4aaf-9ceb-23e81c623f08)
这是我在lazy插件中搜索xmake的结果：
![image](https://github.com/user-attachments/assets/0d9d47ee-eeff-47fb-80de-83fc0b712318)
开启nvim只是很简单的在wezterm中输入`nvim .`，如下：
![image](https://github.com/user-attachments/assets/c2d953ca-388d-4a74-9bb4-5025b82bd552)

**Comment by Mythos-404** [comment]
你试一下`nvim xmake.lua`可以吗

**Comment by Horc-zh** [comment]
> 你试一下`nvim xmake.lua`可以吗

![image](https://github.com/user-attachments/assets/43d33fcf-368c-4ffc-a7f9-bf8c88ddb95b)
![image](https://github.com/user-attachments/assets/a1ac04f3-9225-4c6c-9d3a-09a3e124b15b)

**Comment by Mythos-404** [comment]
命令和保存可以工作吗?

**Comment by Horc-zh** [comment]
> 命令和保存可以工作吗?



是指xmake的命令和保存xmake.lua文件吗？是可以的
![image](https://github.com/user-attachments/assets/0184952d-3dd1-4e58-b3c1-5957c2d5bc1e)
**在我只打开xmake.lua文件的情况下，也就是输入命令`nvim xmake.lua`时：**
奇怪的是，当我按下ctrl + s保存的时候，xmake.nvim插件就可以工作了

![image](https://github.com/user-attachments/assets/472b0814-886a-43f7-a5cc-9c5d81308f5a)
此时还会有相应的命令提示：
![image](https://github.com/user-attachments/assets/1c74ab72-057c-42c8-b458-5202ab455b69)
---


但当我使用`nvim .`打开项目的时候，xmake.nvim插件又不工作了，即使我进入xmake.lua修改了某些行，并且按下ctrl + s会出现右上角的绿色提示，但输入命令`Xmake run`还是没有作用
![image](https://github.com/user-attachments/assets/c5632009-4330-43c7-a618-e25949d82de9)
![image](https://github.com/user-attachments/assets/2e80ef62-7e0d-4370-93ea-76085f578530)

**Comment by Mythos-404** [comment]
因为`Xmake`命令使用的事件是`VimEnter`, 这个事件在启动时是最后加载的, 但是你使用`nvim .`启动项目回导致`BufReadPost`没有启动, 这个时候在打开`xmake.lua`就无法正常加载插件的各种信息了.

这个问题我会尝试修复

**Comment by Horc-zh** [comment]
> 因为`Xmake`命令使用的事件是`VimEnter`, 这个事件在启动时是最后加载的, 但是你使用`nvim .`启动项目回导致`BufReadPost`没有启动, 这个时候在打开`xmake.lua`就无法正常加载插件的各种信息了.
> 
> 这个问题我会尝试修复

好的，谢谢大佬的帮助和插件♪(´▽｀)

**Comment by PFiS1737** [comment]
如修？依然存在此问题。

或许可以考虑将

https://github.com/Mythos-404/xmake.nvim/blob/f16ed9d429b0a53957474309ee27f8ef5c2eec4e/plugin/xmake.lua#L19-L20

从 VimEnter autocmd 移动到 setup, 以通过插件管理器实现懒加载。我们应该总是希望在插件加载后即可使用命令，而不是必须经过 VimEnter 事件。

**Comment by Mythos-404** [comment]
已经没问题了, 我身体一直不好有啥想改得可以提pr
