### ISSUE TITLE
E5560: nvim_err_writeln must not be called in a lua loop callback

### ISSUE THREAD

**Issue by hongxuchen** [Mythos-404/xmake.nvim#3]
Since the `xmake` command may sometime exit with non-zero code, `log.error` can be invoked. But this would emit the error message like `E5560: nvim_err_writeln must not be called in a lua loop callback`. This is due to the fact that `warpper_on_exit` is invoked as a callback inside a luv setting.

A quick fix, as mentioned in [E5560](https://neovim.io/doc/user/lua.html#lua-loop), is to wrap the returned function with `vim.schedule_wrap`:

https://github.com/Mythos-404/xmake.nvim/blob/v2/lua/xmake/async.lua#L29-L47

**Comment by Mythos-404** [comment]
Fixed, thanks for fixing the problem
